### PR TITLE
Customize devise views

### PR DESCRIPTION
**Pull request by Anuth96**
Centered the log in/sign-up views in devise
Screen Shot 2022-06-20 at 12 33 05 pm
!

### CODE REVIEW

**Comment by Anuth96** [comment]
[As a visitor I can visit the (skeletal) home page](https://trello.com/c/ThA5QmYs/1-as-a-visitor-i-can-visit-the-home-page)

**Comment by Anuth96** [comment]
[As a user I can sign in](https://trello.com/c/1S1ngI1A/14-as-a-user-i-can-sign-in)

**Comment by Anuth96** [comment]
[As a user I can sign up](https://trello.com/c/m8Jy4jcF/4-as-a-user-i-can-sign-up)

**Comment by chloechemin** [comment]
Looking great Anuth, well done!

**Pull request merged**
